FROM openjdk:17
COPY pqrs-0.0.1-SNAPSHOT.jar /usr/src/bootdocker/driver2023-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/bootdocker
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/src/bootdocker/driver2023-0.0.1-SNAPSHOT.jar"]